---

NONE:
  description: Blank group required to avoid certain errors

ALL:
  description: All Customers
  username: netadept
  password: netadept
  
MAN:
  description: Temporary group to manually group devices
