---

NONE:
  description: Blank group required to avoid certain errors

ALL:
  description: All Customers
  username: netadept
  password: netadept
  
MAN:
  description: Temporary group to manually group devices

# VENDORS #

CISCO:
  description: CISCO_DEVICES

JUNIPER:
  description: JUNIPER_DEVICES
  password: netadept777!

HUAWEI:
  description: HUAWEI_DEVICES

FORTIGATE:
  description: FORTIGATE_DEVICES
  username: admin
  password: netadept

# SOFTWARE IMAGES #

# HUAWEI #

AR1200:
  platform: huawei_vrp
  description: AR1200
  data:
    image: AR1220E-V200R010C10SPC700

# JUNIPER #

SRX300:
  platform: junos
  description: SRX300 or SRX320
  data:
    image: junos-srxsme-22.4R2-S2.6.tgz

# CISCO #

IMAGE_C800:
  platform: cisco_ios
  data:
    image: c800-universalk9-mz.SPA.158-3.M9.bin
    description: C887VA-K9

IMAGE_ISR4300:
  platform: cisco_ios
  data:
    image: isr4300-universalk9.17.09.04a.SPA.bin
    description: IOS_ISR4300

IMAGE_C3725:
  platform: cisco_ios
  data:
    description: IOS_C3725

IMAGE_VIOS:
  platform: cisco_ios
  data:
    description: vIOS

IMAGE_7:
  platform: forti
  data:
    description: forti

# PRIMARY OR SECONDARY

PRIMARY:
  description: primary device

SECONDARY:
  description: Secondary or backup device

TERSIARY:
  description: tersiary or backup device

# CUSTOMERS

CUSTOMER01:
  description: CUSTOMER01

CUSTOMER02:
  description: CUSTOMER02

CUSTOMER03:
  description: CUSTOMER03
  
CUSTOMER04:
  description: CUSTOMER04

CUSTOMER05:
  description: CUSTOMER05

CUSTOMER06:
  description: CUSTOMER06