---

NONE:
  description: Blank group required to avoid certain errors

ALL:
  description: All Customers
  username: netadept
  password: netadept
  
MAN:
  description: Temporary group to manually group devices

CISCO:
  description: Cisco Devices
  
JUNIPER:
  description: Juniper Devices
  username: netadept
  password: netadept777!

HUAWEI:
  description: Huawei Devices

FORTINET:
  description: Fortinet Devices
  username: admin
  password: netadept777!
  