--- 

NONE: # Empty group for filtering 
  hostname: 
 
SRX_TEST_ROUTER:
  hostname: 192.168.123.200
  platform: junos
  port: 22
  groups:
    - JUNIPER
    - ALL
    - ALL
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: asdfasdf
    grp: Fake_zGroup

CISCO_TEST_ROUTER:
  hostname: 192.168.123.100
  platform: ios
  port: 22
  groups:
    - CISCO
    - ALL
    - ALL
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: afasdf
    grp: asdfasdf
