--- 

NONE: # Empty group for filtering 
  hostname: 
 
CISCO_TEST_ROUTER:
  hostname: 192.168.123.100
  platform: ios
  port: 22
  groups:
    - CISCO
    - MAN
    - ALL
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: africasean
    grp: netAdept_NTWRK

SRX_TEST_ROUTER:
  hostname: 192.168.123.200
  platform: junos
  port: 22
  groups:
    - JUNIPER
    - ALL
    - ALL
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: africasean
    grp: netAdept_NTWRK002

HUAWEI_TEST_ROUTER:
  hostname: 192.168.123.211
  platform: huawei_vrp
  port: 22
  groups:
    - ALL
    - HUAWEI
    - ALL
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: africasean
    grp: netAdept_NTWRK002

CISCO_R02:
  hostname: 192.168.123.211
  platform: ios
  port: 22
  groups:
    - CISCO
    - ALL
    - ALL
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: africasean
    grp: netAdept_NTWRK
