---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "~/netadept/inventory/hosts.yaml"
        group_file: "~/netadept/inventory/groups.yaml"
        defaults_file: "~/netadept/inventory/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 30
