--- 

NONE: # Empty group for filtering 
  hostname: 
 
CISCO_TEST_ROUTER:
  hostname: 192.168.123.100
  platform: ios
  port: 22
  groups:
    - CISCO
    - IMAGE_C800
    - PRIMARY
    - CUSTOMER01
    - ALL
    - ALL
  data:
    ver: 2
    comm: Br1tann1c
    grp: netAdept_NTWRK

SRX_TEST_ROUTER:
  hostname: 192.168.123.200
  platform: junos
  port: 22
  groups:
    - JUNIPER
    - SRX300
    - SECONDARY
    - CUSTOMER02
    - ALL
    - ALL
  data:
    ver: 2
    comm: Br1tann1c
    grp: netAdept_NTWRK

HUAWEI_TEST_ROUTER:
  hostname: 192.168.123.210
  platform: huawei_vrp
  port: 22
  groups:
    - HUAWEI
    - AR1200
    - CUSTOMER01
    - SECONDARY
    - ALL
    - ALL
  data:
    ver: 2
    comm: Br1tann1c
    grp: netAdept_NTWRK

CISCO_TEST_VIOS:
  hostname: 192.168.123.18
  platform: ios
  port: 22
  groups:
    - CISCO
    - IMAGE_VIOS
    - PRIMARY
    - CUSTOMER02
    - ALL
    - ALL
  data:
    ver: 2
    comm: Br1tann1c
    grp: netAdept_NTWRK

CISCO_TEST_C3725:
  hostname: 192.168.123.16
  platform: ios
  port: 22
  groups:
    - CISCO
    - IMAGE_C3725
    - SECONDARY
    - CUSTOMER05
    - ALL
    - ALL
  data:
    ver: 2
    comm: Br1tann1c
    grp: netAdept_NTWRK002

FORTIGATE_TEST_ROUTER:
  hostname: 192.168.123.220
  platform: fortinet
  port: 22
  groups:
    - FORTIGATE
    - IMAGE_7
    - SECONDARY
    - CUSTOMER03
    - ALL
    - ALL
  data:
    ver: 2
    comm: africasean
    grp: netAdept_NTWRK

HUAWEI_TEST_ROUTER999:
  hostname: 192.168.123.219
  platform: huawei_vrp
  port: 22
  groups:
    - TERSIARY
    - CUSTOMER01
    - JUNIPER
    - IMAGE_VIOS
    - ALL
    - ALL
  data:
    ver: 2
    comm: africasean
    grp: netAdept_NTWRK

cisco_device_no1:
  hostname: 192.168.123.120
  platform: ios
  port: 22
  groups:
    - CISCO
    - IMAGE_VIOS
    - TERSIARY
    - ALL
    - ALL
    - ALL
  data:
    ver: 2
    comm: netadept
    grp: netAdept_NTWRK
